package org.example.entities;

/**
 * Model representing a curated activity generated by DeepSeek AI.
 * This is separate from the application's core Activite entity to allow
 * for specific AI-generated metadata if needed.
 */
public class Activity {
    private String name;
    private String description;
    private String category;

    public Activity() {}

    public Activity(String name, String description, String category) {
        this.name = name;
        this.description = description;
        this.category = category;
    }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    @Override
    public String toString() {
        return "Activity{" +
                "name='" + name + '\'' +
                ", category='" + category + '\'' +
                '}';
    }
}
